# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Gateway" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/IncidentService" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/UserService" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/OrganizationService" # Location of package manifests
    schedule:
      interval: "monthly"



