apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
  namespace: example
  labels:
    app: organization-service
  annotations:
spec:
  selector:
    matchLabels:
      app: organization-service
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
      - name: organization-service
        image: $IMAGE_NAME:latest
        imagePullPolicy: Always
        #ports:
        #- containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: example-config